logging:
    level:
        ROOT: DEBUG
        ch.apg.sso: DEBUG

spring:
  jackson:
    serialization:
      indent-output: true

# ===================================================================
# APG specific properties
# ===================================================================
apg:
  url: http://localhost:8081
  # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800
